name: Ready Set Medic
favicon: null
layout_spectrum: 0.75251
typography_spectrum: 0.49399
title: 'Lindsay Somers - Medical consultant for the film & television industry'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#ff0000'
    - '#525252'
    - '#940106'
  brandStrength: 0
  lightness: 0.6392380145844072
  saturation: 0.4797165496274829
  rhythmicContrast: 0.2716324836947024
purpose: []
